export const GET_USER_REQUESTED = "GET_USER_REQUESTED"
export const GET_USER_REJECTED = "GET_USER_REJECTED"
export const GET_USER_FULFILLED = "GET_USER_FULFILLED"
export const SIGNED_OUT = "SIGNED_OUT"
